apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  replicas: 2
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: mohammedaljader2000/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9898
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9898
  type: ClusterIP