apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  selector:
    matchLabels:
      app: course-service
  replicas: 2
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: mohammedaljader2000/course-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8081
  type: ClusterIP