apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
spec:
  selector:
    matchLabels:
      app: job-service
  replicas: 1
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: mohammedaljader2000/job-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8082
  type: ClusterIP