apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
spec:
  selector:
    matchLabels:
      app: mail-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: mohammedaljader2000/mail-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: rabbitmq_port
              value: "5672"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  type: ClusterIP