eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

spring:
  application:
    name: course-service
  rabbitmq:
    addresses: localhost:5672
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5433/courseDB
    username: itskillsnow
  jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  profiles:
      active: default

server:
  port: 8081

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

