stages:
  - build
  - test
  - sonarqube



include:
  - local: 'ITSkillsNow/job-service/.gitlab-ci.yml'
  - local: 'ITSkillsNow/course-service/.gitlab-ci.yml'


sonarqube:
  stage: sonarqube
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    GIT_DEPTH: "0" 
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn -f ITSkillsNow/course-service/pom.xml clean verify -P sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=itskillsnow -Dsonar.login=43804ac61ae83b6ace9759b677b0bde482d6283f

  allow_failure: true
  only:
    - main
