eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

spring:
  application:
    name: user-service
  rabbitmq:
    addresses: localhost:5672
  data:
    mongodb:
      database: User
      authentication-database: admin
      port: 27017
      host: localhost
      auto-index-creation: true
  profiles:
    active: default

server:
  port: 8085


management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

