eureka:
  client:
    enabled: false

spring:
  application:
    name: user-service
  rabbitmq:
    addresses: rabbitmq:5672
  datasource:
    password: M0618678213@
    url: jdbc:postgresql://itskillsnow.postgres.database.azure.com:5432/userDB
    username: itskillsnow
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    azure:
      storage:
        blob:
          account-name: itskillsnowcontainer
          connection-string: BlobEndpoint=https://itskillsnowcontainer.blob.core.windows.net/;QueueEndpoint=https://itskillsnowcontainer.queue.core.windows.net/;FileEndpoint=https://itskillsnowcontainer.file.core.windows.net/;TableEndpoint=https://itskillsnowcontainer.table.core.windows.net/;SharedAccessSignature=sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-07-24T05:17:08Z&st=2023-04-24T21:17:08Z&spr=https&sig=1DbfponbcoeTCm%2FWhWxlyx9GyC605oyrGXp8VxUlQeU%3D

server:
  port: 8085


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0