eureka:
  client:
    enabled: false

spring:
  application:
    name: user-service
  rabbitmq:
    addresses: rabbitmq:5672
  datasource:
    password: M0618678213@
    url: jdbc:postgresql://itskillsnow.postgres.database.azure.com:5432/userDB
    username: itskillsnow
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8085


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0