maven-courseservice:build:
  image: maven:latest
  stage: build
  script: "mvn -f ITSkillsNow/course-service/pom.xml compile"
  only:
    changes:
      - ITSkillsNow/course-service/**/*

maven-courseservice:test:   
  image: maven:latest
  stage: test    
  script: "mvn -f ITSkillsNow/course-service/pom.xml test"
  only:
    changes:
      - ITSkillsNow/course-service/**/*
