version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - run:
          name: Build
          command: mvn -f ITSkillsNow/course-service -B -DskipTests clean package
      - run:
          name: Test
          command: mvn -f ITSkillsNow/course-service test

  sonarcloud:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: SonarCloud Analysis
          command: mvn -f ITSkillsNow/course-service sonar:sonar -Dsonar.projectKey=Course-service -Dsonar.organization=itskillsnow -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c0601c12426c4756b514fd9ed1ea9ff3ecb2304c 

workflows:
  sample:
    jobs:
      - build-and-test
      - sonarcloud:
          requires:
            - build-and-test

