version: '3.9'

services:
  discovery-server:
    image: discovery-server
    container_name: discovery-server
    environment:
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "8761:8761"
    build:
      context: ./discovery-server
      dockerfile: "Dockerfile"
    depends_on:
      - zipkin


  gateway:
    image: gateway
    container_name: gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"
    build:
      context: ./api-gateway
      dockerfile: "Dockerfile"
    depends_on:
      - discovery-server
      - zipkin

  course-service:
    image: course-service
    container_name: course-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
      - spring.rabbitmq.addresses=rabbitmq:5672
    ports:
      - "8081:8081"
    build:
      context: ./course-service
      dockerfile: "Dockerfile"
    depends_on:
      - discovery-server
      - rabbitmq
      - zipkin

  job-service:
    image: job-service
    container_name: job-service
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
      - spring.rabbitmq.addresses=rabbitmq:5672
    ports:
      - "8082:8082"
    build:
      context: ./job-service
      dockerfile: "Dockerfile"
    depends_on:
      - discovery-server
      - rabbitmq
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"