maven-authservice:build:
  image: maven:latest
  stage: build
  script: "mvn -f ITSkillsNow/auth-service/pom.xml compile"
  only:
    changes:
      - ITSkillsNow/auth-service/**/*

maven-authservice:test:
  image: maven:latest
  stage: test    
  script: "mvn -f ITSkillsNow/auth-service/pom.xml test"
  only:
    changes:
      - ITSkillsNow/auth-service/**/*
