eureka:
  client:
    enabled: false

spring:
  application:
    name: job-service
  rabbitmq:
    addresses: http://rabbitmq:5672
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/jobDB
    username: itskillsnow
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    azure:
      storage:
        blob:
          account-name: itskillsnowcontainer
          account-key: gsfqLw++o2GTcAkK7QiCh8yj6bMsfjg8aPYx0sEH3P4DwWifYHe52yaz1LvrGZ1adFMJM3zuwCYg+ASthnBpyw==
          connection-string: BlobEndpoint=https://itskillsnowcontainer.blob.core.windows.net/;QueueEndpoint=https://itskillsnowcontainer.queue.core.windows.net/;FileEndpoint=https://itskillsnowcontainer.file.core.windows.net/;TableEndpoint=https://itskillsnowcontainer.table.core.windows.net/;SharedAccessSignature=sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-04-07T19:54:26Z&st=2023-04-07T11:54:26Z&spr=https&sig=1iTbXykui2%2BjhV204YjRjgN2PakqzQGMeTfruuAJzfQ%3D


server:
  port: 8082

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

