eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

spring:
  application:
    name: job-service
  rabbitmq:
    addresses: localhost:5672
  datasource:
    url: jdbc:h2:mem:jobDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-ui

  cloud:
    azure:
      storage:
        blob:
          account-name: itskillsnowcontainer
          connection-string: BlobEndpoint=https://itskillsnowcontainer.blob.core.windows.net/;QueueEndpoint=https://itskillsnowcontainer.queue.core.windows.net/;FileEndpoint=https://itskillsnowcontainer.file.core.windows.net/;TableEndpoint=https://itskillsnowcontainer.table.core.windows.net/;SharedAccessSignature=sv=2021-12-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2023-07-24T05:17:08Z&st=2023-04-24T21:17:08Z&spr=https&sig=1DbfponbcoeTCm%2FWhWxlyx9GyC605oyrGXp8VxUlQeU%3D

server:
  port: 8082

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


