eureka:
  client:
    enabled: false

server:
  port: 9898

spring:
  application:
    name: auth-service
  rabbitmq:
    addresses: rabbitmq:5672
  datasource:
    password: M0618678213@
    url: jdbc:postgresql://itskillsnow.postgres.database.azure.com:5432/authDB
    username: itskillsnow
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true



management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans