spring:
  application:
    name: discovery-server
  profiles:
    active: default

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans