name: Trigger auto deployment for job-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/job-service-AutoDeployTrigger-eda43fb3-1e38-4c77-842a-016001d3a493.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.JOBSERVICE_REGISTRY_USERNAME }}
          password: ${{ secrets.JOBSERVICE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mohammedaljader2000/mohammedaljader2000/job-service:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JOBSERVICE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n job-service -g ITSkillsNow --server docker.io --username  ${{ secrets.JOBSERVICE_REGISTRY_USERNAME }} --password ${{ secrets.JOBSERVICE_REGISTRY_PASSWORD }}
            az containerapp update -n job-service -g ITSkillsNow --image mohammedaljader2000/mohammedaljader2000/job-service:${{ github.sha }}
